# Use Ubuntu as the base image
FROM ubuntu:latest

WORKDIR /var/www/html/

# Update the package list and install Apache
RUN apt-get update && \
    apt-get install -y apache2 && \
    apt-get clean


# Copy application code into the container
COPY . .

# Expose the default Apache port
EXPOSE 80

# Command to Start Apache in the foreground
ENTRYPOINT ["apachectl", "-D", "FOREGROUND"]